export const ERROR_CODE_MAP: Record<string, string> = {
  // === 登入、註冊與權限 ===
  NO_TOKEN: "尚未登入或登入已過期，請重新登入。",
  INVALID_TOKEN: "登入資訊無效，請重新登入",
  TOKEN_EXPIRED: "登入已過期，請重新登入",
  INVALID_REFRESH_TOKEN: "登入狀態異常，請重新登入",
  REFRESH_TOKEN_EXPIRED: "登入已過期，請重新登入",
  REFRESH_TOKEN_REQUIRED: "登入資訊不足，請重新登入",
  TOKEN_REFRESH_FAILED: "更新登入狀態失敗，請重新登入。",
  UNAUTHORIZED: "請先登入後再繼續",
  FORBIDDEN: "您目前無法執行這項操作",
  ADMIN_ACCESS_REQUIRED: "您沒有執行此操作的權限",
  ADMIN_ROLE_REQUIRED: "此功能僅限管理員使用",
  INVALID_CREDENTIALS: "帳號或密碼不正確，請重新輸入。",
  LOGIN_FAILED: "登入時發生問題，請稍後再試。",
  LOGOUT_FAILED: "登出失敗，請稍後再試。",
  USER_ALREADY_EXISTS: "此 Email 已經註冊過，請直接登入。",
  USER_ID_MISSING: "找不到登入資訊，請重新登入",
  USER_NOT_FOUND: "找不到此會員資料",
  USER_REGISTRATION_FAILED: "註冊失敗，請稍後再試。",
  PASSWORD_RESET_REQUEST_FAILED: "重設密碼信件發送失敗，請稍後再試。",
  INVALID_RESET_TOKEN: "重設密碼連結無效或已過期，請重新申請。",
  PASSWORD_UPDATE_FAILED: "更新密碼失敗，請稍後再試。",

  // === 購物車 ===
  ADD_TO_CART_FAILED: "加入購物車時發生問題，請稍後再試。",
  CART_ACCESS_UNAUTHORIZED: "請先登入後再查看購物車。",
  CART_ITEM_FIELDS_REQUIRED: "請先選擇商品與數量",
  INVALID_QUANTITY: "數量必須是正整數，請重新輸入。",
  CART_ITEM_NOT_FOUND: "找不到指定的購物車商品，請重新整理後再試。",
  CART_NOT_FOUND: "找不到您的購物車，請重新整理頁面。",
  CLEAR_CART_FAILED: "清空購物車失敗，請稍後再試。",
  INVALID_LOCAL_CART_DATA: "購物車資料格式有誤，請重新加入商品。",
  REMOVE_FROM_CART_FAILED: "移除購物車商品失敗，請稍後再試。",
  SYNC_CART_FAILED: "同步購物車失敗，請稍後再試。",
  UPDATE_CART_ITEM_QUANTITY_FAILED: "更新商品數量失敗，請稍後再試。",

  // === 商品 ===
  PRODUCT_ID_REQUIRED: "缺少商品編號，請重新操作",
  PRODUCT_DATA_REQUIRED: "請填寫完整商品資料",
  INVALID_PRODUCT_ID: "商品資料有誤，請重新整理後再試。",
  INVALID_PRODUCT_IDS: "商品資料有誤，請重新選擇商品。",
  INVALID_PRODUCT_UPDATE_DATA: "請提供要更新的商品內容",
  PRODUCT_NOT_FOUND: "找不到此商品",
  PRODUCT_CREATE_FAILED: "新增商品失敗，請稍後再試。",
  PRODUCT_DELETE_FAILED: "刪除商品失敗，請稍後再試。",
  PRODUCT_FETCH_FAILED: "取得商品資料失敗，請稍後再試。",
  PRODUCTS_FETCH_FAILED: "取得商品列表失敗，請稍後再試。",
  PRODUCT_UPDATE_FAILED: "更新商品失敗，請稍後再試。",

  // === 訂單與結帳 ===
  INVALID_ORDER_ID: "訂單資料有誤，請重新整理後再試。",
  ORDER_CREATE_FAILED: "建立訂單失敗，請稍後再試。",
  ORDER_FETCH_FAILED: "取得訂單資料失敗，請稍後再試。",
  ORDER_NOT_FOUND: "找不到此筆訂單",
  ORDER_UPDATE_FAILED: "更新訂單失敗，請稍後再試。",
  ORDER_UPDATE_FORBIDDEN: "您無法修改這筆訂單",
  ORDER_VIEW_FORBIDDEN: "您無法查看這筆訂單",
  ORDERS_FETCH_FAILED: "取得訂單列表失敗，請稍後再試。",
  USER_ORDERS_FETCH_FAILED: "取得您的訂單失敗，請稍後再試。",
  PAYMENT_CREATE_FAILED: "建立付款資料失敗，請稍後再試。",

  // === 優惠碼 ===
  COUPON_FIELDS_REQUIRED: "請完整填寫優惠碼資料欄位",
  INVALID_DISCOUNT_TYPE: "優惠類型錯誤，請重新確認",
  INVALID_DISCOUNT_VALUE: "折扣數值無效，請重新輸入",
  INVALID_PERCENTAGE_DISCOUNT: "百分比折扣不可超過 100%",
  INVALID_MIN_PURCHASE_AMOUNT: "最低消費金額不可小於 0",
  INVALID_EXPIRY_DATE: "優惠碼到期日格式不正確",
  COUPON_CODE_ALREADY_EXISTS: "此優惠碼已存在，請使用其他代碼。",
  COUPON_CREATE_FAILED: "建立優惠碼失敗，請稍後再試。",
  COUPONS_FETCH_FAILED: "取得優惠碼列表失敗，請稍後再試。",
  INVALID_COUPON_ID: "優惠碼編號格式錯誤",
  COUPON_NOT_FOUND: "找不到此優惠碼",
  COUPON_NOT_ACTIVE: "此優惠碼目前未啟用",
  COUPON_DELETE_FAILED: "停用優惠碼失敗，請稍後再試。",
  COUPON_CODE_REQUIRED: "請先輸入優惠碼",
  INVALID_SUBTOTAL: "訂單金額格式錯誤，請重新整理後再試。",
  COUPON_EXPIRED: "優惠碼已過期",
  COUPON_MIN_PURCHASE_NOT_MET: "尚未達到優惠碼的最低消費門檻",
  INVALID_COUPON_DISCOUNT_AMOUNT: "優惠碼折扣金額無效",
  COUPON_VALIDATE_FAILED: "優惠碼驗證失敗，請稍後再試。",

  // === 最新消息 ===
  INVALID_NEWS_UPDATE_DATA: "請提供要更新的最新消息內容",
  NEWS_CREATE_FAILED: "建立最新消息失敗，請稍後再試。",
  NEWS_DELETE_FAILED: "刪除最新消息失敗，請稍後再試。",
  NEWS_DETAIL_FETCH_FAILED: "取得最新消息內容失敗，請稍後再試。",
  NEWS_FETCH_FAILED: "取得最新消息失敗，請稍後再試。",
  NEWS_NOT_FOUND: "找不到這則最新消息",
  NEWS_UPDATE_FAILED: "更新最新消息失敗，請稍後再試。",

  // === 其他 ===
  BAD_REQUEST: "請求內容有誤，請確認後再試一次。",
  INTERNAL_SERVER_ERROR: "系統忙碌中，請稍後再試。",
  NOT_FOUND: "找不到您要的資料",
  IMAGE_FILE_REQUIRED: "請先選擇要上傳的圖片",
  IMAGE_UPLOAD_FAILED: "圖片上傳失敗，請稍後再試。",
};
